# Stubs for potranslator (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .potranslator import PoTranslator
from .polib import POFile
from pathlib import WindowsPath
from typing import Text, Tuple, Any
import gettext

__author__: Text
__email__: Text
__version__: Text
__copyright__: Text
__credits__: Tuple[Text]
__license__: Text
__maintainer__: Text
__status__: Text
_RESOURCE_PACKAGE: Text = __name__
_TRANSLATIONS_PATH: WindowsPath
json_file: WindowsPath
SUPPORTED_LANGUAGES: Tuple[Text]
_TRANSLATED_LANGUAGES: Tuple[Text]
_user_locale: Text
_POTRANSLATOR_TRANSLATIONS: gettext.GNUTranslations

def _get_user_locale() -> Text: ...

def _getdoc(object: Any) -> Text: ...


