# Stubs for potranslator.cli (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def main(args: Optional[Any] = ...) -> None: ...
